/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var MessageType_pb = require('./MessageType_pb.js');
goog.exportSymbol('proto.DeleteDeg2FriendRS', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DeleteDeg2FriendRS = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DeleteDeg2FriendRS, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DeleteDeg2FriendRS.displayName = 'proto.DeleteDeg2FriendRS';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DeleteDeg2FriendRS.prototype.toObject = function(opt_includeInstance) {
  return proto.DeleteDeg2FriendRS.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DeleteDeg2FriendRS} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DeleteDeg2FriendRS.toObject = function(includeInstance, msg) {
  var f, obj = {
    errInfo: (f = msg.getErrInfo()) && MessageType_pb.ErrorInfo.toObject(includeInstance, f),
    userId: jspb.Message.getField(msg, 2),
    peerId: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DeleteDeg2FriendRS}
 */
proto.DeleteDeg2FriendRS.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DeleteDeg2FriendRS;
  return proto.DeleteDeg2FriendRS.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DeleteDeg2FriendRS} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DeleteDeg2FriendRS}
 */
proto.DeleteDeg2FriendRS.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new MessageType_pb.ErrorInfo;
      reader.readMessage(value,MessageType_pb.ErrorInfo.deserializeBinaryFromReader);
      msg.setErrInfo(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUserId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPeerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DeleteDeg2FriendRS.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DeleteDeg2FriendRS.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DeleteDeg2FriendRS} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DeleteDeg2FriendRS.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      MessageType_pb.ErrorInfo.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint64(
      3,
      f
    );
  }
};


/**
 * optional MessageType.ErrorInfo err_info = 1;
 * @return {?proto.MessageType.ErrorInfo}
 */
proto.DeleteDeg2FriendRS.prototype.getErrInfo = function() {
  return /** @type{?proto.MessageType.ErrorInfo} */ (
    jspb.Message.getWrapperField(this, MessageType_pb.ErrorInfo, 1));
};


/** @param {?proto.MessageType.ErrorInfo|undefined} value */
proto.DeleteDeg2FriendRS.prototype.setErrInfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.DeleteDeg2FriendRS.prototype.clearErrInfo = function() {
  this.setErrInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.DeleteDeg2FriendRS.prototype.hasErrInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required uint64 user_id = 2;
 * @return {number}
 */
proto.DeleteDeg2FriendRS.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.DeleteDeg2FriendRS.prototype.setUserId = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.DeleteDeg2FriendRS.prototype.clearUserId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.DeleteDeg2FriendRS.prototype.hasUserId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required uint64 peer_id = 3;
 * @return {number}
 */
proto.DeleteDeg2FriendRS.prototype.getPeerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.DeleteDeg2FriendRS.prototype.setPeerId = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.DeleteDeg2FriendRS.prototype.clearPeerId = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.DeleteDeg2FriendRS.prototype.hasPeerId = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto);
